version: "3.7"

services:
  database:
    image: mysql:8.0
    platform: linux/amd64
    command:
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=codetest
      - MYSQL_USER=codetest
      - MYSQL_PASSWORD=swordfish
    ports:
      - "8080:3306"
    restart: always
  webserver:
    image: puckel/docker-airflow:latest
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: airflow-container
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./logs-volume:/usr/local/airflow/logs
    ports:
      - 8081:8080
    restart: always
    depends_on:
      - database
